### ISSUE TITLE
Jenkins test-harness functional test checking happy day scenario

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#10]
Just to show how tests can be done, we will create a test-harness test that shows the happy day scenario and that everything seems to work.

The test will create a job, configure it to a real live service, run a job and get the risk indicator.

We will need to get access to a service, a project ID, have credentials (we will pass in secretly to the test) to implement this.

**Comment by MadsNielsen** [comment]
This is closed via. #22 since the full suite should cover the happy day scenario.
