### ISSUE TITLE
Build setup

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#12]
We need as a minimum to have automated builds and integration, and a job where users and reviewers can pick up the latest `.hpi`  file to install on Jenkins to review the plugin and try it out.

One job, standard maven command and archived artifacts. Public available Jenkins job on our CI infrastructure.

**Comment by geoffwhittington** [comment]
Yes, public is fine.

**Comment by MadsNielsen** [comment]
I've added travis and setup releasese. I've added the commands in the readme
