### ISSUE TITLE
UI feedback from MoM

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/sdelements-plugin#15]
### Icons

- Dimension: 64 x 64 px 
- Transparent background
- .svg, .png
- 3 set of icons, PASS, FAIL, UNDETERMINED

## Individual build

![build](https://user-images.githubusercontent.com/1484793/38738689-11211fd4-3f33-11e8-8162-d4dc47d37cb3.png)

Text for icon on the left: 
https://github.com/Praqma/sdelements-plugin/blob/8a642a30812ce150ecb99ecf399599742ee401e0/src/main/java/io/jenkins/plugins/sdelements/SDElementsRiskIndicatorBuildAction.java#L39-L42  

Icon logic:
https://github.com/Praqma/sdelements-plugin/blob/8a642a30812ce150ecb99ecf399599742ee401e0/src/main/java/io/jenkins/plugins/sdelements/SDElementsRiskIndicatorBuildAction.java#L31-L37

## Global configuration page

Each field has a help `html` file named `help-<name_of_field>.html`: https://github.com/Praqma/sdelements-plugin/tree/master/src/main/resources/io/jenkins/plugins/sdelements/SDElementsConnection 

So to update the help it's simply to add text to the files already present in that folder. Same convention everywhere. 

![globalconfig](https://user-images.githubusercontent.com/1484793/38738694-139b2f98-3f33-11e8-8d3c-c5c868fe59d7.png)

## Job configuration page
![jobconfig](https://user-images.githubusercontent.com/1484793/38738698-16669b22-3f33-11e8-95ed-c9d2393f6274.png)

Same with the help, files are located in this folder: https://github.com/Praqma/sdelements-plugin/tree/master/src/main/resources/io/jenkins/plugins/sdelements/SDElements

## Job overview page

![projectdisplay](https://user-images.githubusercontent.com/1484793/38738702-18853198-3f33-11e8-8399-a9fcd3c7c0cc.png)

Link text: 
https://github.com/Praqma/sdelements-plugin/blob/8a642a30812ce150ecb99ecf399599742ee401e0/src/main/java/io/jenkins/plugins/sdelements/SDElementsRiskIndicatorProjectAction.java#L25-L31

Icon logic:
https://github.com/Praqma/sdelements-plugin/blob/8a642a30812ce150ecb99ecf399599742ee401e0/src/main/java/io/jenkins/plugins/sdelements/SDElementsRiskIndicatorProjectAction.java#L17-L23

**Comment by buep** [comment]
I had some extra thought around the look and feel... I would like to recommend some adjustments.

The left-side menu on the Jenkins job overview page above should probably just contain your SD Elements icon, and it should _not_ contain any status. The icon should always be yours. Just say `SD Elements` and link to the project URL in the configured server setup, so a user can always click it and go the project front page in SD Elements.

Then the right hand side summary, also on the Jenkins job overview page (just above the workspace icon) should contain both your logo and a status summary. That is the usual way plugins do it I think.
This means something like this:
```
[logo icon] SD Elements Risk Status:
    [status icon] [status text]
```
where we need a status icon for both compliant and non-compliant and undetermined. The status text should follow your wording in SD Elements.

There wasn't many example screen shots from a lot of plugins, but I think the Jenkins Robot plugin explains it well. Here is their Job overview page: https://wiki.jenkins.io/display/JENKINS/Robot+Framework+Plugin?preview=/47087692/47382535/project_page.png 
The have more status than you, but the follow the concepts above.

Drilling down to the Individual build page, I suggest the same layout as above. The difference between the individual builds and the job overview page is that the latter always shows results from latest builds, while the individual build pages persist the result at for that specific build.

The build page for the Jenkins Robot Framework plugin do this as well: https://wiki.jenkins.io/display/JENKINS/Robot+Framework+Plugin?preview=/47087692/47382536/build_page.png

**Comment by buep** [comment]
@geoffwhittington assigned it to you to give us inputs, and maybe do as much as possible yourself. We might need @MadsNielsen to change the layout a bit if you follow recommendations above - we can create a new issue on that when we have icons etc.

**Comment by mrrathwell** [comment]
Sorry - not quite following the where the new icons will appear in this screen shot. Will they be where SD Elements is now (on the left side)  or will they appear where Build #38 is in the above shot and then reused for the build history? I'm assuming the three status icons appear where the build icon appears now and that you need an SD Elements product icon to go beside SDE? 

For Archangel and myself (who are new to Jenkins), confirming the terminology:

- Pass means the build will run successfully
- Fail means the build has been failed
- Unstable means the build will run successfully but has issues to be aware of

**Comment by mrrathwell** [comment]
![image](https://user-images.githubusercontent.com/38660823/39251037-51e25a4c-4870-11e8-9809-52ce36bee4f1.png)

**Comment by mrrathwell** [comment]
We will create all icons as
64 x 64 pixels
They contain a transparent background
They will be provided as an SVG or PNG (probably a PNG)

**Comment by aacuison** [comment]
I've attached the icons in both .svg and .png files, with 64x64 px dimensions and transparent bg.

[icons.zip](https://github.com/Praqma/sdelements-plugin/files/1964562/icons.zip)

**Comment by buep** [comment]
@aacuison thanks, do you also have the SD Element logo or icon we can use for the sidebar. I guess it is the atom-like logo you have.

**Comment by aacuison** [comment]
Oh yes, here you go!

[sde-icon.zip](https://github.com/Praqma/sdelements-plugin/files/1964827/sde-icon.zip)

**Comment by buep** [comment]
I'm closing this - we will implement the new layout in #25.

I believe @MadsNielsen have time for it tomorrow.
