### ISSUE TITLE
Rename plugin and update description

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#19]
Propose artifact name changes is kept as `sdelements` in Maven https://github.com/Praqma/sdelements-plugin/blob/master/pom.xml#L11

Most plugins do not use dash and space not allowed (https://updates.jenkins.io/download/plugins/).

The name though should be with space: `SD Elements Plugin` https://github.com/Praqma/sdelements-plugin/blob/master/pom.xml#L18

The description should say: `Jenkins integration for SD Elements risk assessment from Security Compass`

I think this is the conclusion on our drop 1 chat in #13

**Comment by MadsNielsen** [comment]
I've fixed the issues outlined here. So closing.
