### ISSUE TITLE
Add more tests using our test account on SD Elements online 

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#22]
I would like the following tests to be able to run automatically before we release. Run them with maven command passing in our api token on command line so we don't expose it in the project itself.

Implement the still missing tests from the following list, using Jenkins test harness and job configured to do:

* get project id of passing project
* get project id of failing project
* get project id of project still not completed mandatory survey questions
* invalid url
* invalid project id
* failed authentication

**Comment by buep** [comment]
After the demo and setup of new project in SD Elements as part of #13 we're not able to develop more tests.

**Comment by MadsNielsen** [comment]
@buep is this not part of the MVP?

**Comment by buep** [comment]
I didn't add the label because it wasn't part of the original MVP planning. It will still be part of our drop 2 effort, thus it is workable as soon at you set an estimate.

**Comment by MadsNielsen** [comment]
This is closed in commit: 5b7eae77a564392b9635407b3317f698f4bdd7b9

I mislabled the commit in the instance it's related to #22 instead of #5
