### ISSUE TITLE
Update readme with API docs and usage pattern

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/sdelements-plugin#24]

**Comment by buep** [comment]
Yes, we want to explain why the API is made as it is, and how easy it will be to use for other CI integrations.

**Comment by MadsNielsen** [comment]
Theres a couple things that need clarification here after thinking about what we talked about i don't think this is relevant atm. 

1) Packaging? We do not package the API in a separate JAR, so at the moment it's not easy to use the API in other projects. Do we want to do this as part of the MVP???
2) We talked about doing it this way, just having at as a separate Java package in code in order not to complicate matters during development and manage interproject dependencies.

**Comment by buep** [comment]
> Packaging? We do not package the API in a separate JAR, so at the moment it's not easy to use the API in other projects. Do we want to do this as part of the MVP???

No I don't think so at the moment.

But let's make an issue on it, describing it it needed to use in other CI systems, and when it is done it should be separately released to official maven repo somewhere or the Jenkins CI infrastructure as separate module.
