### ISSUE TITLE
Plugin link is 'null' on hover

### ISSUE THREAD

**Issue by geoffwhittington** [Praqma/sdelements-plugin#28]
The `(from SD Elements Plugin)` link renders as follows:

* Project-level:  http://localhost:8080/job/C-Sharp%20Application/null
* System-level: http://localhost:8080/null

Where is the link meant to send a user?

![image](https://user-images.githubusercontent.com/1770544/39589732-0313fa7a-4ecd-11e8-9160-9bd4a968c67d.png)

**Comment by MadsNielsen** [comment]
@geoffwhittington Oh i can see what the problem is. The project file is missing an `<url>` element. 

This url usually points to the official wiki page, so i'll add the url for you. 

The official url for the wiki should be: `https://wiki.jenkins-ci.org/display/JENKINS/SDElements+Plugin`

**Comment by geoffwhittington** [comment]
Fixed, thank-you!
