### ISSUE TITLE
Implement risk indicator query library

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#5]
Implement a separate library, inside the plugin as a package that later could be extracted and replaced, to talk to SD Elements and query the risk indicator.

In the plugin we will be having three statuses:

* pass (or what is is called in SD Elements)
* blocked (or what is it called in SD Elements)
* unavailable (which we set in Jenkins when we can't retrieve the status (e.g. service temporarily down, failed authentication etc.)

**Comment by buep** [comment]
I think we have all three status - so that is fine.

Only one minor thing:
> So we return that in case we can determine the status (PASS,FAIL), and use the default state as a fallback. If something goes wrong. 

We should not use the default state as fall-back, the third option is `undetermined` as I believe you call it and should only be used when we know what is going wrong and it is a situation we handle.
But that said, if something unknown happens, we will also use `undetermined` but will handle the exception different basically explaining something wrong, we don't know what and give some message about the exception.

So this means that you have 3 status, but there are actually 4 code paths through it.

**Comment by MadsNielsen** [comment]
After discussions with @buep and @kryptag we've decided on the following:

1. The api will return an ENUM in case of proper interaction with api. 
2. The api will throw named checked exception for handled exceptions (wrong project id, missing authentication etc...), and a subclass for unhandled exceptions (mid transport error, metor impact?). They can then be treated differently in the publisher.

This can be closed with https://github.com/Praqma/sdelements-plugin/commit/03f5b932b40b89333b8f596a8e445420e207c64a
