### ISSUE TITLE
Override global server configuration pr. job basis

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#8]
In case users don't want to use the administrator configured Jenkins global list of SD Element services, it should be possible to add a specific one to each job to use instead.

**Comment by geoffwhittington** [comment]
I'm not sure we discussed this today. However, I think the usual method is ok: people can only choose a server that is defined at the global level.

**Comment by buep** [comment]
Nope, I forgot in our meeting so planned to mention it in mail.

I agree - we stick with the usual way other plugins do. So I'm closing this.
