### ISSUE TITLE
Implement authentication part of risk indicator query

### ISSUE THREAD

**Issue by buep** [Praqma/sdelements-plugin#9]
Usually authentication is a bit more work, so we will implement it separately.

We will add testing as part of this running tests towards an online SD Element service configured for us.

Failure test:
 - wrong project id
 - service not available wrong url
 - service not available credentials

For all these scenarios we should ensure that the user is informed in a nice way in the Jenkins build console, the plugin emits a warnings in the Jenkins log and we should explain to the user what went wrong (auth? unavailable? ...)

Risk indicator becomes `unavailable` if something fails.

**Comment by geoffwhittington** [comment]
The error message won't reveal the token.

The token is only ever disclosed to an API caller when there is a deliberate request to create / regenerate one. Further, the endpoints that create / regenerate a token only accept authentication using basic or session-based authentication.

**Comment by geoffwhittington** [comment]
Regarding what behaviour to create there's a failure talking to the server: I would want to know what most other plugins do in this case, if you have that information. I believe failing the build is the right thing here.

**Comment by buep** [comment]
I also believe we came to the conclusion in #13 that we should fail the build.

The reason is if you configure your Jenkins job to do something, and it can't do it - it should fail. Like when you ask it to build.
Other post-build steps like the Git Publisher will also fail the build if you ask it to tag the repo, but it can't. This normal behavior in many plugins.

It's important for me as user though, that I get a good reason. I think Mads covered those.

**Comment by MadsNielsen** [comment]
I believe this was fixed with #5 and also i've implemented tests for the known errors that can happen when using the API: https://github.com/Praqma/sdelements-plugin/blob/master/src/test/java/io/jenkins/plugins/sdelements/api/SDElementsLibraryTest.java
